name: Release Module on Steam

on:
  workflow_call:
    inputs:
      mod_description:
        required: false
        type: string
        default: ''
      artifact_name:
        required: true
        type: string

jobs:
  publish-on-steam:
    name: Publish Module on Steam
    runs-on: ubuntu-latest
    steps:
    
    - name: Setup
      uses: butr/actions-common-setup@v2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Download Module artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
        path: ./artifact

    - uses: actions/setup-node@v3.4.1
      with:
        node-version: 16

    - run: |
        mkdir steam-totp
        cat << EOT > steam-totp/package.json
        {
          "name": "steam-totp-gen",
          "version": "1.0.0",
          "description": "",
          "main": "index.js",
          "dependencies": {
            "steam-totp": "^2.1.2"
          }
        }
        
    - run: |
        cat << EOT > steam-totp/index.js
        var code = require('steam-totp').generateAuthCode(process.argv[0]);
        console.log(`::add-mask::${code}`);
        console.log(`::set-output name=totp::${code}`);

    - run: cd ./steam-totp && npm ci && node ./src/index.js {{ secrets.STEAM_AUTH_CODE }}

    - uses: CyberAndrii/setup-steamcmd@v1

    - run: |
        cat << EOT > item.vdf
        "workshopitem"
        {
            "appid" "261550"
            "publishedfileid" "2859188632"
            "contentfolder" "./artifact"
            "changenote" "${{ steps.version.outputs.mod_description }}"
        }
        EOT

    - run: steamcmd +login ${{ secrets.STEAM_LOGIN }} ${{ secrets.STEAM_PASSWORD }} +workshop_build_item "./item.vdf" +quit
