name: Verify Credentials for NexusMods

on:
  workflow_call:
    secrets:
      NEXUSMODS_APIKEY:
        required: true
      NEXUSMODS_COOKIE_NEXUSID:
        required: true
      NEXUSMODS_COOKIE_SID_DEVELOP:
        required: true

jobs:
  verify-credentials-nexusmods:
    name: Verify Credentials for NexusMods
    runs-on: ubuntu-latest
    steps:

    - name: Setup .NET 6
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 6.x.x

    - name: Install Digitalroot.ModUploader
      run: dotnet tool install -g Digitalroot.ModUploader
      shell: pwsh

    - name: Check Digitalroot.ModUploader credentials
      run: drmu nexusmods check;
      env:
        NEXUSMOD_API_KEY: ${{ secrets.NEXUSMOD_API_KEY }}
        NEXUSMOD_COOKIE_NEXUSID: ${{ secrets.NEXUSMOD_COOKIE_NEXUSID }}
        NEXUSMOD_COOKIE_SID_DEVELOP: ${{ secrets.NEXUSMOD_COOKIE_SID_DEVELOP }}
      shell: pwsh
