name: Verify Credentials for NexusMods

on:
  workflow_call:
    secrets:
      NEXUSMODS_API_KEY:
        required: true
      NEXUSMOD_SESSION_COOKIE:
        required: true

jobs:
  verify-credentials-nexusmods:
    name: Verify Credentials for NexusMods
    runs-on: ubuntu-latest
    steps:

    - name: Setup .NET 6
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 6.x.x

    - name: Install Digitalroot.ModUploader
      run: dotnet tool install -g Digitalroot.ModUploader
      shell: pwsh

    - name: Check Digitalroot.ModUploader credentials
      run: drmu nexusmods check;
      env:
        NEXUSMOD_API_KEY: ${{ secrets.NEXUSMODS_API_KEY }}
        NEXUSMOD_SESSION_COOKIE: ${{ secrets.NEXUSMOD_SESSION_COOKIE }}
      shell: pwsh
